### ISSUE TITLE
Unable to Upgrade

### ISSUE THREAD

**Issue by andrew-s-taylor** [latracal/grigora#2]
The link to purchase the Pro version goes to a dead page.  Can this be fixed, or if no longer in development, could the source for Pro be released (or just the options removed)

Thanks

Andrew

**Comment by latracal** [comment]
Hi Andrew,

Both Grigora and its Pro version are deprecated and we're actively developing a new theme and ecosystem around https://github.com/latracal/grigora-blocks . Yes, we did develop the Pro version and it was working but its no longer in development. Please drop an email to pratik@latracal.com if you're still looking for it, I'll be happy to send it.

Regards,
Pratik
